### ISSUE TITLE
Sample response for TURNSERVER API

### ISSUE THREAD

**Issue by hassaan-dev** [MidEndProject/node-apprtc#4]
Hi,

Can you tell me sample response for TurnServer API?

I am getting following Error

Cannot create RTCPeerConnection; WebRTC is not supported by this browser.

my json response is below, please confirm this is valid format or not

`{"urls":["turn:35.***.***.211:443?transport=udp","turn:35.***.***.211:443:443?transport=tcp","turn:35.***.***.211:443:443"],"username":"test","credential":"password"}`

**Comment by fitraditya** [comment]
Hi,

I think you get 2 different errors.

The first one indicating that your browser is not compatible with webrtc api. What browser did you use?

And the second issue is relate to TURN REST API which is broken. I'll fix it.

**Comment by hassaan-dev** [comment]
I am using Google Chrome Version 67.0.3396.99 (Official Build) (64-bit).

When I can except this fix of TURN REST API?

**Comment by hassaan-dev** [comment]
I also have tried this with the latest one, **Google Chrome Version 68.0.3440.75 (Official Build) (64-bit)**

**Comment by hassaan-dev** [comment]
There is application error demo link.

Can you tell me what is response of this URL? https://node-apprtc.herokuapp.com/?turn

**Comment by fitraditya** [comment]
I've made some fixes and change the demo link.
Please pull updates and check README to get new demo link.

**Comment by hassaan-dev** [comment]
There is application error demo link.
Let me try it dear 👍 
Can you tell me what is response of this URL? https://node-apprtc.herokuapp.com/?turn

**Comment by hassaan-dev** [comment]
Let me try it 👍

**Comment by hassaan-dev** [comment]
Its working now. Thanks 💯
