### ISSUE TITLE
WSS server

### ISSUE THREAD

**Issue by anuragdalia** [MidEndProject/node-apprtc#7]
I was wondering if you could point me to the repo of the code thats hosted at this endpoint 

WSS_HOST_PORT_PAIRS: ['node-apprtc-ws.herokuapp.com'],

^this line is from your config

**Comment by fitraditya** [comment]
Hi,

This is the repository that you need https://github.com/fitraditya/collider.
It's written using go.

**Comment by anuragdalia** [comment]
oh okay thanks .. I thought you had something written with hapi and socketio/hapiio 

if I am able to do that i'll send in a pr
